<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.msb</groupId>
    <artifactId>EmbeddedBanking</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>EmbeddedBanking</name>
    <description>EmbeddedBanking</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <!-- flyway -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-flyway</artifactId>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
        </dependency>
        <!-- JWT -->
        <dependency>
            <artifactId>jjwt-api</artifactId>
            <groupId>io.jsonwebtoken</groupId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <artifactId>jjwt-impl</artifactId>
            <groupId>io.jsonwebtoken</groupId>
            <scope>runtime</scope>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <artifactId>jjwt-jackson</artifactId>
            <groupId>io.jsonwebtoken</groupId>
            <scope>runtime</scope>
            <version>0.11.5</version>
        </dependency>
        <!-- OpenAPI/Swagger -->
        <dependency>
            <artifactId>springdoc-openapi-ui</artifactId>
            <groupId>org.springdoc</groupId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!-- Open api generator plugin -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.17.0</version>

                <configuration>
                    <generatorName>spring</generatorName>
                    <apiPackage>com.msb.embeddedbanking.api</apiPackage>
                    <output>${project.build.directory}/generated-sources/openapi</output>
                    <generateApis>true</generateApis>
                    <generateModels>false</generateModels>
                    <generateSupportingFiles>false</generateSupportingFiles>
                    <generateApiTests>false</generateApiTests>
                    <generateApiDocumentation>false</generateApiDocumentation>
                    <generateModelTests>false</generateModelTests>
                    <generateModelDocumentation>false</generateModelDocumentation>
                    <skipValidateSpec>false</skipValidateSpec>

                    <configOptions>
                        <dateLibrary>java8</dateLibrary>
                        <hideGenerationTimestamp>true</hideGenerationTimestamp>
                        <interfaceOnly>true</interfaceOnly>
                        <java8>false</java8>
                        <performBeanValidation>true</performBeanValidation>
                        <serializableModel>false</serializableModel>
                        <skipDefaultInterface>true</skipDefaultInterface>
                        <useBeanValidation>true</useBeanValidation>
                        <useOptional>false</useOptional>
                        <useSpringBoot3>true</useSpringBoot3>
                        <useTags>true</useTags>
                        <strictSpecBehavior>true</strictSpecBehavior>
                    </configOptions>
                </configuration>

                <executions>
                    <!-- Xác thực -->
                    <execution>
                        <id>generate-auth-api</id>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/api-spec/api-spec-auth.yaml
                            </inputSpec>

                            <schemaMappings>
                                <!-- Common -->
                                <schemaMapping>
                                    ErrorResponse=com.msb.embeddedbanking.controller.common.ErrorResponse
                                </schemaMapping>
                                <!-- Auth -->
                                <schemaMapping>
                                    LoginRequest=com.msb.embeddedbanking.controller.request.auth.LoginRequest
                                </schemaMapping>
                                <schemaMapping>
                                    RefreshTokenRequest=com.msb.embeddedbanking.controller.request.auth.RefreshTokenRequest
                                </schemaMapping>
                                <schemaMapping>
                                    LoginResponse=com.msb.embeddedbanking.controller.response.auth.LoginResponse
                                </schemaMapping>
                            </schemaMappings>
                        </configuration>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>

                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
