SPRING_PROFILES_ACTIVE: local

# Database Configuration
DB_URL: jdbc:postgresql://localhost:5432/EB
DB_USERNAME: postgres
DB_PASSWORD: 123456

# JPA Configuration
JPA_DDL_AUTO: none
JPA_SHOW_SQL: true

# Flyway Configuration
FLYWAY_ENABLED: true
FLYWAY_BASELINE_ON_MIGRATE: true
FLYWAY_BASELINE_VERSION: 0
FLYWAY_VALIDATE_ON_MIGRATE: true

#JWT
JWT_SECRET: w/D+LwUzxeJr6VgE1nMypoa7sXXQWGp9GcYygFrQneMewtkFwwFNvayNcGHgep4N4gBp/4MEtC2VBCyU6MOR6w==
JWT_ACCESS_TOKEN_EXPIRATION: 3600000
JWT_REFRESH_TOKEN_EXPIRATION: 604800000