name: Embedded Banking CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Show project files
        run: ls -la

      - name: Check Java version
        run: java -version